### PR TITLE
Error in parse-classes

### PR DESCRIPTION
**Pull request by povloid**
After upgrade hipo a give this error

old
               class="nav navbar-nav navbar-right

new
              class="nav navbar-nav.navbar-right"

### CODE REVIEW

**Comment by jeluard** [comment]
Nice catch! Do you mind adding a test for this?

**Comment by jeluard** [comment]
Thanks!

**Comment by povloid** [comment]
Than your!  I use this library in my project. As I'll be free then try to write tests.

**Comment by jeluard** [comment]
Don't worry about tests I [updated one](https://github.com/jeluard/hipo/blob/master/test/hipo/hiccup_test.cljs#L21) to catch the issue.

**Pull request merged**
